version: '3.6'

services:
  django:
    container_name: django_server
    build: .
    image: pdfconverter
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app/
    ports:
      - "8008:8000"